# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '006_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1143, 816)
        self.click_me_button = QtWidgets.QPushButton(Form)
        self.click_me_button.setGeometry(QtCore.QRect(220, 580, 561, 181))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.click_me_button.setFont(font)
        self.click_me_button.setObjectName("click_me_button")
        self.hello_world_label = QtWidgets.QLabel(Form)
        self.hello_world_label.setGeometry(QtCore.QRect(310, 180, 511, 281))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.hello_world_label.setFont(font)
        self.hello_world_label.setObjectName("hello_world_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.click_me_button.setText(_translate("Form", "Appuie !"))
        self.hello_world_label.setText(_translate("Form", "Hello World!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
